/** Loading the two surfaces the parity check compares, and the registry between them. */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { allOperations } from "@galaxyproject/galaxy-ops";
import { buildServer } from "../../src/server";
import {
  describe as describeValue,
  isPlainObject,
  read,
  surfaceByName,
  NORMALIZATION_RULES,
  type DivergenceKind,
  type JsonSchema,
  type Normalization,
  type NormalizationRuleName,
  type Surface,
  type ToolAnnotations,
  type ToolContract,
} from "./compare";

/**
 * Generated by `uv run python -m tests.surface_manifest` in mcp-server-galaxy-py.
 * Living outside this package is the point: it is the other server's contract, and
 * a copy kept on this side is what rotted last time.
 */
const MANIFEST_URL = new URL(
  "../../../../../mcp-server-galaxy-py/tests/testdata/mcp-surface.json",
  import.meta.url,
);

const REGISTRY_URL = new URL("../fixtures/accepted-divergences.json", import.meta.url);

export interface ManifestTool {
  name: string;
  tags: string[];
  /** Set when the Python server registers the tool only under an optional extra. */
  conditionalOn?: string;
  /** Written only for a tool that declares a lower bound on the Galaxy it runs against. */
  requires?: { galaxy: string };
  /** The MCP annotations the Python tool advertises; empty when it advertises none. */
  annotations: ToolAnnotations;
  inputSchema: JsonSchema;
}

export interface Manifest {
  source: string;
  toolCount: number;
  tools: ManifestTool[];
}

export type DivergenceStatus = "intentional" | "pending-port" | "pending-decision" | "unreviewed-gap";

export const DIVERGENCE_STATUSES: readonly DivergenceStatus[] = [
  "intentional",
  "pending-port",
  "pending-decision",
  "unreviewed-gap",
];

export interface AcceptedDivergence {
  tool: string;
  param: string | null;
  kind: DivergenceKind;
  observed: string;
  status: DivergenceStatus;
  reason: string;
}

export interface NormalizationRule {
  enabled: boolean;
  status: DivergenceStatus;
  reason: string;
}

export interface Ratchet {
  unreviewedGaps: number;
}

export interface Registry {
  normalization: Record<NormalizationRuleName, NormalizationRule>;
  ratchet: Ratchet;
  divergences: AcceptedDivergence[];
}

/**
 * The status the registry is not allowed to accumulate: a difference the comparator
 * found and nobody has ruled on. Everything else is somebody's decision and can be
 * argued with; this one is just a pile.
 */
export const RATCHETED_STATUS: DivergenceStatus = "unreviewed-gap";

/**
 * How many divergences of the ratcheted status the registry says it may hold.
 * Read rather than reached for, so everything that shows this number -- the check
 * and the report -- refuses the same unreadable registry with the same words.
 */
export function ratchetCeiling(registry: Registry): number {
  const node = registry as unknown as Record<string, unknown>;
  const declared = (read(node, "ratchet", "object", "the registry") ?? {}) as Record<
    string,
    unknown
  >;
  const allowed = read(declared, "unreviewedGaps", "count", "the registry's ratchet");
  if (allowed === undefined) {
    throw new Error(
      `the registry does not say how many "${RATCHETED_STATUS}" divergences it may hold, and ` +
        "that number is the only thing stopping the pile growing",
    );
  }
  return allowed as number;
}

/**
 * What the ratchet has to say about the registry as it stands.
 *
 * Counted over the registry's own entries rather than over the live divergences,
 * which is the same number: the two tests either side of this one fail the moment
 * the registry lists a divergence the surfaces no longer support or misses one they
 * do. A malformed declaration throws instead -- a count that cannot be read is not
 * a parity problem, it is a registry nobody can check.
 */
export function ratchetProblems(registry: Registry): string[] {
  const ceiling = ratchetCeiling(registry);
  const held = registry.divergences.filter((d) => d.status === RATCHETED_STATUS).length;
  if (held > ceiling) {
    return [
      `the registry holds ${held} "${RATCHETED_STATUS}" divergences where ${ceiling} is the most ` +
        "it may hold. A new one needs somebody to read both sides and give it a reviewed status " +
        "and a reason, or the gap closed in the op -- not a bigger number in `ratchet`.",
    ];
  }
  if (held < ceiling) {
    return [
      `the registry holds ${held} "${RATCHETED_STATUS}" divergences and says it may hold ` +
        `${ceiling}. Lower \`ratchet.unreviewedGaps\` to ${held}: a number left above the real ` +
        "count is room for the next one to arrive unnoticed.",
    ];
  }
  return [];
}

function readJson<T>(url: URL, what: string): T {
  const path = fileURLToPath(url);
  try {
    return JSON.parse(readFileSync(path, "utf8")) as T;
  } catch (err) {
    throw new Error(`cannot read the ${what} at ${path}: ${(err as Error).message}`);
  }
}

export function loadManifest(): Manifest {
  return readJson<Manifest>(MANIFEST_URL, "Python surface manifest");
}

export function loadRegistry(): Registry {
  return readJson<Registry>(REGISTRY_URL, "accepted-divergence registry");
}

/** Every rule the comparator knows about, switched by the registry. */
export function normalizationFrom(registry: Registry): Normalization {
  const node = registry as unknown as Record<string, unknown>;
  const written = (read(node, "normalization", "object", "the registry") ?? {}) as Record<
    string,
    unknown
  >;
  // Read as the registry's own entries: looked up on an object, a rule named like
  // something every object answers to would be found whether it wrote one or not.
  const declared = new Map(Object.entries(written));
  const switches: [NormalizationRuleName, boolean][] = [];
  for (const name of NORMALIZATION_RULES) {
    const rule = declared.get(name);
    if (!rule) throw new Error(`the registry does not declare the "${name}" normalization rule`);
    if (!isPlainObject(rule)) {
      throw new Error(`the registry's "${name}" rule is ${describeValue(rule)}, not a rule`);
    }
    const enabled = read(rule, "enabled", "boolean", `the registry's "${name}" rule`);
    if (enabled === undefined) {
      throw new Error(`the registry does not say whether "${name}" is enabled`);
    }
    switches.push([name, enabled as boolean]);
  }
  return Object.fromEntries(switches) as Normalization;
}

export function pythonSurface(manifest: Manifest): Surface {
  const node = manifest as unknown as Record<string, unknown>;
  const tools = read(node, "tools", "list", "the manifest");
  if (tools === undefined) throw new Error("the manifest does not list any tools");
  return surfaceByName(
    (tools as unknown[]).map((entry, index) => {
      const where = `the manifest's tool ${index}`;
      if (!isPlainObject(entry)) {
        throw new Error(`${where} is ${describeValue(entry)}, not a tool`);
      }
      const name = read(entry, "name", "string", where);
      if (name === undefined) throw new Error(`${where} has no name`);
      const about = `${name as string} (manifest)`;
      // Each of these is read rather than defaulted: a manifest that stopped
      // recording one would quietly take the comparison back to guessing.
      const annotations = read(entry, "annotations", "object", about);
      if (annotations === undefined) {
        throw new Error(`the manifest does not say what ${name as string} advertises`);
      }
      const inputSchema = read(entry, "inputSchema", "object", about);
      if (inputSchema === undefined) {
        throw new Error(`the manifest does not say what ${name as string} takes`);
      }
      const tags = read(entry, "tags", "names", about);
      if (tags === undefined) {
        throw new Error(`the manifest does not say how ${name as string} is tagged`);
      }
      // Absent for most tools, so unlike the fields above this one is read rather
      // than demanded; what it has to look like when it is there is the comparison's call.
      const requires = read(entry, "requires", "object", about) as
        | { galaxy: string }
        | undefined;
      // Written only for a tool whose result the generator could read off one dict literal,
      // so absent here means "not stated" rather than "returns nothing".
      const resultFields = read(entry, "resultFields", "names", about) as string[] | undefined;
      return [
        name as string,
        {
          inputSchema: inputSchema as JsonSchema,
          annotations: annotations as ToolAnnotations,
          tags: tags as string[],
          requires,
          resultFields,
        },
      ] as [string, ToolContract];
    }),
    "the manifest",
  );
}

/**
 * What an MCP client actually sees from this package -- asked of a running server
 * rather than rebuilt from the op shapes, so a registration bug shows up here too.
 */
export async function typescriptSurface(): Promise<Surface> {
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  const server = buildServer({ baseUrl: "https://galaxy.invalid", apiKey: "not-used" });
  const client = new Client({ name: "parity-check", version: "0" });
  await Promise.all([server.connect(serverTransport), client.connect(clientTransport)]);
  // MCP has no field for what a tool needs from the server, so this side declares it
  // on the op and nowhere else -- over the wire it survives only as a sentence in the
  // description, and `surface.test.ts` is what holds that sentence to the declaration.
  const declaredRequirements = new Map(allOperations.map((op) => [op.name, op.requires]));
  // Also op-side only: MCP has no field for the shape of a result either.
  const declaredResults = new Map(allOperations.map((op) => [op.name, op.resultFields]));
  try {
    const { tools } = await client.listTools();
    return surfaceByName(
      tools.map((t) => {
        const advertised = t as unknown as Record<string, unknown>;
        const where = `${t.name} (advertised)`;
        if (!declaredRequirements.has(t.name)) {
          throw new Error(
            `${t.name} is advertised but is not a registered op, so there is nothing to read ` +
              "what it needs from the server off",
          );
        }
        return [
          t.name,
          {
            inputSchema: (read(advertised, "inputSchema", "object", where) ?? {}) as JsonSchema,
            // No tags: an MCP server advertises the read/write split as a hint or not at all.
            annotations: (read(advertised, "annotations", "object", where) ??
              {}) as ToolAnnotations,
            requires: declaredRequirements.get(t.name),
            resultFields: declaredResults.get(t.name),
          },
        ] as [string, ToolContract];
      }),
      "the advertised tools",
    );
  } finally {
    await client.close();
    await server.close();
  }
}
